services:
  - type: web
    name: retrievus-frontend
    env: static
    region: oregon
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_APP_NAME
        value: Retrievus
    autoDeploy: true